name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"   # toutes les 12h
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output: pacman-contribution-graph.svg

      - name: Move file to output folder
        run: |
          mkdir -p output
          mv pacman-contribution-graph.svg output/

      - name: Push pacman svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
